use std::collections::HashMap;

use wdn_physics::tile::{
    adjacency::{Adjacency, TileAdjacency},
    material::TileKind,
    position::TileChunkOffset,
    storage::{TileData, TileStorage},
};

use crate::tile::WALL_OFFSET;

const EMPTY: u16 = 0;
const EMPTY_SOUTHWALLCORNER: u16 = 1;
const EMPTY_SOUTHWALLHORIZONTAL: u16 = 2;
const EMPTY_SOUTHSTAIRN: u16 = 3;
const EMPTY_SOUTHSTAIRNWALL: u16 = 4;
const EMPTY_SOUTHSTAIRNDOUBLE: u16 = 5;
const EMPTY_SOUTHSTAIRSWALL: u16 = 6;
const EMPTY_SOUTHSTAIRE: u16 = 7;
const EMPTY_SOUTHSTAIRW: u16 = 8;
const WALLCORNER: u16 = 9;
const WALLHORIZONTAL: u16 = 10;
const WALLCORNER_SOUTHDOOR: u16 = 11;
const WALLVERTICAL: u16 = 12;
const WALLINVERSECORNER: u16 = 13;
const WALLVERTICAL_EASTDOOR: u16 = 14;
const WALLVERTICAL_SOUTHEASTWALL: u16 = 15;

const WALLFULL: u16 = 16;
const WALLVERTICAL_SOUTHEASTWALL_EASTDOOR: u16 = 17;
const WALLCORNER_EASTDOOR: u16 = 18;
const WALLHORIZONTAL_SOUTHDOOR: u16 = 19;
const WALLCORNER_SOUTHDOOR_EASTDOOR: u16 = 20;
const WALLCORNER_SOUTHSTAIRN: u16 = 21;
const WALLHORIZONTAL_SOUTHSTAIRN: u16 = 22;
const WALLCORNER_SOUTHSTAIRN_EASTDOOR: u16 = 23;
const WALLCORNER_SOUTHSTAIRNWALL: u16 = 24;
const WALLHORIZONTAL_SOUTHSTAIRNWALL: u16 = 25;
const WALLCORNER_SOUTHSTAIRNWALL_EASTDOOR: u16 = 26;
const WALLCORNER_SOUTHSTAIRNDOUBLE: u16 = 27;
const WALLHORIZONTAL_SOUTHSTAIRNDOUBLE: u16 = 28;
const WALLCORNER_SOUTHSTAIRNDOUBLE_EASTDOOR: u16 = 29;
const WALLCORNER_SOUTHSTAIRSWALL: u16 = 30;
const WALLHORIZONTAL_SOUTHSTAIRSWALL: u16 = 31;

const WALLCORNER_SOUTHSTAIRSWALL_EASTDOOR: u16 = 32;
const WALLCORNER_SOUTHSTAIRE: u16 = 33;
const WALLHORIZONTAL_SOUTHSTAIRE: u16 = 34;
const WALLCORNER_SOUTHSTAIRE_EASTDOOR: u16 = 35;
const WALLCORNER_SOUTHSTAIRW: u16 = 36;
const WALLHORIZONTAL_SOUTHSTAIRW: u16 = 37;
const WALLCORNER_SOUTHSTAIRW_EASTDOOR: u16 = 38;
const DOOR_SOUTHWALLCORNER: u16 = 39;
const DOOR_SOUTHWALLHORIZONTAL: u16 = 40;
const STAIRN: u16 = 41;
const STAIRN_EASTWALL: u16 = 42;
const STAIRN_EASTSTAIR: u16 = 43;
const STAIRN_SOUTHWALLCORNER: u16 = 44;
const STAIRN_SOUTHWALLCORNER_EASTWALL: u16 = 45;
const STAIRN_SOUTHWALLCORNER_EASTSTAIR: u16 = 46;
const STAIRN_SOUTHWALLHORIZONTAL: u16 = 47;

const STAIRN_SOUTHWALLHORIZONTAL_EASTWALL: u16 = 48;
const STAIRN_SOUTHWALLHORIZONTAL_EASTSTAIR: u16 = 49;
const STAIRN_SOUTHSTAIRN: u16 = 50;
const STAIRN_SOUTHSTAIRN_EASTWALL: u16 = 51;
const STAIRN_SOUTHSTAIRN_EASTSTAIR: u16 = 52;
const STAIRN_SOUTHSTAIRNWALL: u16 = 53;
const STAIRN_SOUTHSTAIRNWALL_EASTWALL: u16 = 54;
const STAIRN_SOUTHSTAIRNWALL_EASTSTAIR: u16 = 55;
const STAIRN_SOUTHSTAIRNDOUBLE: u16 = 56;
const STAIRN_SOUTHSTAIRNDOUBLE_EASTWALL: u16 = 57;
const STAIRN_SOUTHSTAIRNDOUBLE_EASTSTAIR: u16 = 58;
const STAIRN_SOUTHSTAIRSWALL: u16 = 59;
const STAIRN_SOUTHSTAIRSWALL_EASTWALL: u16 = 60;
const STAIRN_SOUTHSTAIRSWALL_EASTSTAIR: u16 = 61;
const STAIRN_SOUTHSTAIRE: u16 = 62;
const STAIRN_SOUTHSTAIRE_EASTWALL: u16 = 63;

const STAIRN_SOUTHSTAIRE_EASTSTAIR: u16 = 64;
const STAIRN_SOUTHSTAIRW: u16 = 65;
const STAIRN_SOUTHSTAIRW_EASTWALL: u16 = 66;
const STAIRN_SOUTHSTAIRW_EASTSTAIR: u16 = 67;
const STAIRS: u16 = 68;
const STAIRS_EASTWALL: u16 = 69;
const STAIRS_EASTSTAIR: u16 = 70;
const STAIRS_SOUTHWALLCORNER: u16 = 71;
const STAIRS_SOUTHWALLCORNER_EASTWALL: u16 = 72;
const STAIRS_SOUTHWALLCORNER_EASTSTAIR: u16 = 73;
const STAIRS_SOUTHWALLHORIZONTAL: u16 = 74;
const STAIRS_SOUTHWALLHORIZONTAL_EASTWALL: u16 = 75;
const STAIRS_SOUTHWALLHORIZONTAL_EASTSTAIR: u16 = 76;
const STAIRS_SOUTHSTAIRN: u16 = 77;
const STAIRS_SOUTHSTAIRN_EASTWALL: u16 = 78;
const STAIRS_SOUTHSTAIRN_EASTSTAIR: u16 = 79;

const STAIRS_SOUTHSTAIRNWALL: u16 = 80;
const STAIRS_SOUTHSTAIRNWALL_EASTWALL: u16 = 81;
const STAIRS_SOUTHSTAIRNWALL_EASTSTAIR: u16 = 82;
const STAIRS_SOUTHSTAIRNDOUBLE: u16 = 83;
const STAIRS_SOUTHSTAIRNDOUBLE_EASTWALL: u16 = 84;
const STAIRS_SOUTHSTAIRNDOUBLE_EASTSTAIR: u16 = 85;
const STAIRS_SOUTHSTAIRSWALL: u16 = 86;
const STAIRS_SOUTHSTAIRSWALL_EASTWALL: u16 = 87;
const STAIRS_SOUTHSTAIRSWALL_EASTSTAIR: u16 = 88;
const STAIRS_SOUTHSTAIRE: u16 = 89;
const STAIRS_SOUTHSTAIRE_EASTWALL: u16 = 90;
const STAIRS_SOUTHSTAIRE_EASTSTAIR: u16 = 91;
const STAIRS_SOUTHSTAIRW: u16 = 92;
const STAIRS_SOUTHSTAIRW_EASTWALL: u16 = 93;
const STAIRS_SOUTHSTAIRW_EASTSTAIR: u16 = 94;
const STAIRE: u16 = 95;

const STAIRE_SOUTHWALLCORNER: u16 = 96;
const STAIRE_SOUTHWALLHORIZONTAL: u16 = 97;
const STAIRE_SOUTHWALLFULL: u16 = 98;
const STAIRE_SOUTHSTAIRN: u16 = 99;
const STAIRE_SOUTHSTAIRNWALL: u16 = 100;
const STAIRE_SOUTHSTAIRNWALLFULL: u16 = 101;
const STAIRE_SOUTHSTAIRNDOUBLE: u16 = 102;
const STAIRE_SOUTHSTAIRSWALL: u16 = 103;
const STAIRE_SOUTHSTAIRE: u16 = 104;
const STAIRE_SOUTHSTAIRW: u16 = 105;
const STAIRW: u16 = 106;
const STAIRW_NORTHWALL: u16 = 107;
const STAIRW_NORTHSTAIR: u16 = 108;
const STAIRW_SOUTHWALLCORNER: u16 = 109;
const STAIRW_SOUTHWALLCORNER_NORTHWALL: u16 = 110;
const STAIRW_SOUTHWALLCORNER_NORTHSTAIR: u16 = 111;

const STAIRW_SOUTHWALLHORIZONTAL: u16 = 112;
const STAIRW_SOUTHWALLHORIZONTAL_NORTHWALL: u16 = 113;
const STAIRW_SOUTHWALLHORIZONTAL_NORTHSTAIR: u16 = 114;
const STAIRW_SOUTHWALLFULL: u16 = 115;
const STAIRW_SOUTHWALLFULL_NORTHWALL: u16 = 116;
const STAIRW_SOUTHWALLFULL_NORTHSTAIR: u16 = 117;
const STAIRW_SOUTHSTAIRN: u16 = 118;
const STAIRW_SOUTHSTAIRN_NORTHWALL: u16 = 119;
const STAIRW_SOUTHSTAIRN_NORTHSTAIR: u16 = 120;
const STAIRW_SOUTHSTAIRNWALL: u16 = 121;
const STAIRW_SOUTHSTAIRNWALL_NORTHWALL: u16 = 122;
const STAIRW_SOUTHSTAIRNWALL_NORTHSTAIR: u16 = 123;
const STAIRW_SOUTHSTAIRNWALLFULL: u16 = 124;
const STAIRW_SOUTHSTAIRNWALLFULL_NORTHWALL: u16 = 125;
const STAIRW_SOUTHSTAIRNWALLFULL_NORTHSTAIR: u16 = 126;
const STAIRW_SOUTHSTAIRNDOUBLE: u16 = 127;

const STAIRW_SOUTHSTAIRNDOUBLE_NORTHWALL: u16 = 128;
const STAIRW_SOUTHSTAIRNDOUBLE_NORTHSTAIR: u16 = 129;
const STAIRW_SOUTHSTAIRSWALL: u16 = 130;
const STAIRW_SOUTHSTAIRSWALL_NORTHWALL: u16 = 131;
const STAIRW_SOUTHSTAIRSWALL_NORTHSTAIR: u16 = 132;
const STAIRW_SOUTHSTAIRE: u16 = 133;
const STAIRW_SOUTHSTAIRE_NORTHWALL: u16 = 134;
const STAIRW_SOUTHSTAIRE_NORTHSTAIR: u16 = 135;
const STAIRW_SOUTHSTAIRW: u16 = 136;
const STAIRW_SOUTHSTAIRW_NORTHWALL: u16 = 137;
const STAIRW_SOUTHSTAIRW_NORTHSTAIR: u16 = 138;

pub fn sprite_offset(storage: &TileStorage, offset: TileChunkOffset, tile: TileData) -> (u16, u16) {
    todo!()
}

#[test]
fn test_sprite_offset() {}
