use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::Path;

use wdn_enumerate::{
    BaseSprite, TopSprite, TopSpriteCenter, TopSpriteEast, TopSpriteSouth, TopSpriteSouthEast,
};

use crate::spritesheet::{
    TILE_HEIGHT, TILE_WIDTH, center_label, center_top_label, east_label, east_top_label,
    extract_labeled_parts, render_to_pixmap, resolve_layers, south_east_top_label, south_label,
    south_top_label, top_sprite_pattern,
};

/// The solid fill color used for wall/ceiling "Top" surfaces in the top parts SVG.
const TARGET_COLOR: (u8, u8, u8) = (0x33, 0x3c, 0x43);
/// Pixels below this alpha are treated as absent, so antialiased edges don't create spurious
/// isolated specks.
const ALPHA_THRESHOLD: u8 = 128;
/// Allowed per-channel rounding error when un-premultiplying antialiased edge pixels.
const COLOR_TOLERANCE: i32 = 4;

/// Caches, per part-asset label, whether it draws only `#333c43ff` and its own pixel mask.
type FieldCache = HashMap<&'static str, (bool, Vec<bool>)>;

struct FieldInfo {
    name: &'static str,
    /// Whether every opaque pixel this field draws (rendered on its own) is `#333c43ff`.
    pure: bool,
    /// This field's own `#333c43ff` pixels, rendered in isolation from the rest of the sprite.
    mask: Vec<bool>,
}

/// For each `(base, top)` pairing actually produced by the game, checks each of `top`'s
/// non-`None` fields. A field that draws any color other than `#333c43ff` is always kept
/// (never considered for removal). A field drawn entirely in `#333c43ff` is redundant only if
/// both: its own area is already entirely covered by `base`'s own `#333c43ff` pixels (so
/// drawing it again changes nothing), and it isn't 4-connected to a `#333c43ff` area
/// contributed by one of the sprite's other fields that *isn't* covered by `base` either (that
/// would be a real, otherwise-disconnected area of color, not just a redundant duplicate). A
/// field is only ever removed if this holds for every `base` it's paired with. Prints a report
/// of the redundant fields.
pub fn report_redundant_top_fields(
    pairs: &HashSet<(BaseSprite, TopSprite)>,
    base_parts_path: &Path,
    top_parts_path: &Path,
) -> std::io::Result<()> {
    let redundant_everywhere = analyze(pairs, base_parts_path, top_parts_path)?;

    let mut redundant_count = 0;
    for (&(top, field), &redundant) in &redundant_everywhere {
        if redundant {
            println!("redundant top field `{field}` on {top:?}");
            redundant_count += 1;
        }
    }
    println!("{redundant_count} redundant top sprite fields");

    Ok(())
}

/// Generates `impl TopSprite { pub fn simplify(self) -> Self }`, resetting every field
/// [`report_redundant_top_fields`] identifies as redundant to `None`, and writes the generated
/// source to `output_path`.
pub fn generate_simplify(
    pairs: &HashSet<(BaseSprite, TopSprite)>,
    base_parts_path: &Path,
    top_parts_path: &Path,
    output_path: &Path,
) -> std::io::Result<()> {
    let redundant_everywhere = analyze(pairs, base_parts_path, top_parts_path)?;

    let mut simplified_by_top: HashMap<TopSprite, TopSprite> = HashMap::new();
    for &(_, top) in pairs {
        simplified_by_top.entry(top).or_insert_with(|| {
            ["center", "south", "south_east", "east"]
                .into_iter()
                .filter(|field| {
                    redundant_everywhere
                        .get(&(top, field))
                        .copied()
                        .unwrap_or(false)
                })
                .fold(top, with_field_none)
        });
    }

    let mut arms = String::new();
    for (&top, &simplified) in &simplified_by_top {
        if simplified == top {
            continue;
        }

        arms.push_str(&format!(
            "            {} => {},\n",
            top_sprite_pattern(top),
            top_sprite_pattern(simplified)
        ));
    }

    let mut code = String::new();
    code.push_str("// Generated by `cargo run -p wdn-enumerate`. Do not edit by hand.\n\n");
    code.push_str("use crate::{\n");
    code.push_str(
        "    TopSprite, TopSpriteCenter, TopSpriteEast, TopSpriteSouth, TopSpriteSouthEast,\n",
    );
    code.push_str("};\n\n");
    code.push_str("impl TopSprite {\n");
    code.push_str(
        "    /// Removes `#333c43ff`-only fields whose area is disconnected from the sprite's other\n",
    );
    code.push_str(
        "    /// `#333c43ff` content (see `contiguity::report_redundant_top_fields`), deduplicating\n",
    );
    code.push_str("    /// tiles beyond what `normalize()` alone catches.\n");
    code.push_str("    pub fn simplify(self) -> Self {\n");
    code.push_str("        match self {\n");
    code.push_str(&arms);
    code.push_str("            _ => self,\n");
    code.push_str("        }\n    }\n}\n");

    fs::write(output_path, code)
}

/// Returns `top` with `field` reset to its `None` variant.
fn with_field_none(top: TopSprite, field: &str) -> TopSprite {
    match field {
        "center" => TopSprite {
            center: TopSpriteCenter::None,
            ..top
        },
        "south" => TopSprite {
            south: TopSpriteSouth::None,
            ..top
        },
        "south_east" => TopSprite {
            south_east: TopSpriteSouthEast::None,
            ..top
        },
        "east" => TopSprite {
            east: TopSpriteEast::None,
            ..top
        },
        _ => unreachable!("unknown TopSprite field `{field}`"),
    }
}

/// For every `(base, top)` pairing, determines whether each of `top`'s fields is redundant (see
/// [`report_redundant_top_fields`]), and returns whether that holds across *every* pairing seen
/// for that `(top, field)`.
fn analyze(
    pairs: &HashSet<(BaseSprite, TopSprite)>,
    base_parts_path: &Path,
    top_parts_path: &Path,
) -> std::io::Result<HashMap<(TopSprite, &'static str), bool>> {
    let base_parts = extract_labeled_parts(&std::fs::read_to_string(base_parts_path)?);
    let top_parts = extract_labeled_parts(&std::fs::read_to_string(top_parts_path)?);
    let mut field_cache = FieldCache::new();
    let mut base_mask_cache: HashMap<BaseSprite, Vec<bool>> = HashMap::new();

    let mut redundant_everywhere: HashMap<(TopSprite, &'static str), bool> = HashMap::new();
    for &(base, top) in pairs {
        let base_mask = base_mask_cache
            .entry(base)
            .or_insert_with(|| base_mask(base, &base_parts, base_parts_path))
            .clone();

        for (field, redundant) in field_redundancy(
            top,
            &base_mask,
            &top_parts,
            top_parts_path,
            &mut field_cache,
        ) {
            redundant_everywhere
                .entry((top, field))
                .and_modify(|still_redundant| *still_redundant &= redundant)
                .or_insert(redundant);
        }
    }

    Ok(redundant_everywhere)
}

/// Renders `base` alone and returns its `#333c43ff` pixel mask.
fn base_mask(
    base: BaseSprite,
    base_parts: &HashMap<String, String>,
    base_parts_path: &Path,
) -> Vec<bool> {
    let labels = [
        center_label(base.center),
        south_label(base.south),
        east_label(base.east),
    ];
    let layers = resolve_layers(&labels, base_parts, base_parts_path);
    mask_from_layers(&layers)
}

/// For each of `top`'s present fields, reports whether it's redundant against this specific
/// `base_mask`: entirely covered by `base_mask`, and not 4-connected to another field's
/// `#333c43ff` area that isn't covered by `base_mask` either.
fn field_redundancy(
    top: TopSprite,
    base_mask: &[bool],
    top_parts: &HashMap<String, String>,
    top_parts_path: &Path,
    field_cache: &mut FieldCache,
) -> Vec<(&'static str, bool)> {
    let fields: Vec<FieldInfo> = [
        (
            "center",
            top.center != TopSpriteCenter::None,
            center_top_label(top.center),
        ),
        (
            "south",
            top.south != TopSpriteSouth::None,
            south_top_label(top.south),
        ),
        (
            "south_east",
            top.south_east != TopSpriteSouthEast::None,
            south_east_top_label(top.south_east),
        ),
        (
            "east",
            top.east != TopSpriteEast::None,
            east_top_label(top.east),
        ),
    ]
    .into_iter()
    .filter(|&(_, present, _)| present)
    .map(|(name, _, label)| {
        let (pure, mask) = field_cache
            .entry(label)
            .or_insert_with(|| isolated_field(label, top_parts, top_parts_path))
            .clone();
        FieldInfo { name, pure, mask }
    })
    .collect();

    fields
        .iter()
        .enumerate()
        .filter(|&(_, field)| field.pure)
        .map(|(index, field)| {
            let contained_in_base = field
                .mask
                .iter()
                .zip(base_mask)
                .all(|(&is_set, &in_base)| !is_set || in_base);

            let others_extra_not_in_base = fields
                .iter()
                .enumerate()
                .filter(|&(other_index, _)| other_index != index)
                .fold(vec![false; field.mask.len()], |acc, (_, other)| {
                    or_masks(acc, &other.mask)
                })
                .iter()
                .zip(base_mask)
                .map(|(&is_set, &in_base)| is_set && !in_base)
                .collect::<Vec<_>>();

            let redundant =
                contained_in_base && !is_contiguous(&field.mask, &others_extra_not_in_base);
            (field.name, redundant)
        })
        .collect()
}

fn or_masks(mut a: Vec<bool>, b: &[bool]) -> Vec<bool> {
    for (a, &b) in a.iter_mut().zip(b) {
        *a |= b;
    }
    a
}

/// Renders `label`'s own SVG fragment alone (transparent background), returning whether it's
/// drawn entirely in `#333c43ff` and its own `#333c43ff` pixel mask.
fn isolated_field(
    label: &str,
    parts: &HashMap<String, String>,
    parts_path: &Path,
) -> (bool, Vec<bool>) {
    let layer = parts
        .get(label)
        .unwrap_or_else(|| panic!("missing part `{label}` in {}", parts_path.display()));
    let mask = mask_from_layers(std::slice::from_ref(layer));
    let pure = pixmap_from_layers(std::slice::from_ref(layer))
        .data()
        .chunks_exact(4)
        .all(matches_target_or_empty);

    (pure, mask)
}

fn mask_from_layers(layers: &[String]) -> Vec<bool> {
    pixmap_from_layers(layers)
        .data()
        .chunks_exact(4)
        .map(|pixel| pixel[3] >= ALPHA_THRESHOLD && matches_target_or_empty(pixel))
        .collect()
}

fn pixmap_from_layers(layers: &[String]) -> resvg::tiny_skia::Pixmap {
    let mut body = String::new();
    for layer in layers {
        body.push_str(layer);
        body.push('\n');
    }

    let svg = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n\
         <svg width=\"{TILE_WIDTH}\" height=\"{TILE_HEIGHT}\" viewBox=\"0 0 {TILE_WIDTH} {TILE_HEIGHT}\" \
         xmlns=\"http://www.w3.org/2000/svg\" xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\" \
         xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\">\n{body}</svg>\n"
    );

    render_to_pixmap(&svg)
}

fn matches_target_or_empty(pixel: &[u8]) -> bool {
    let alpha = pixel[3] as i32;
    if alpha == 0 {
        return true;
    }

    let unpremultiply = |channel: u8| channel as i32 * 255 / alpha;
    (unpremultiply(pixel[0]) - TARGET_COLOR.0 as i32).abs() <= COLOR_TOLERANCE
        && (unpremultiply(pixel[1]) - TARGET_COLOR.1 as i32).abs() <= COLOR_TOLERANCE
        && (unpremultiply(pixel[2]) - TARGET_COLOR.2 as i32).abs() <= COLOR_TOLERANCE
}

/// Whether any `true` pixel in `a` is 4-adjacent to a `true` pixel in `b`.
fn is_contiguous(a: &[bool], b: &[bool]) -> bool {
    let width = TILE_WIDTH as usize;
    let height = TILE_HEIGHT as usize;

    for y in 0..height {
        for x in 0..width {
            if !a[y * width + x] {
                continue;
            }

            for (nx, ny) in neighbors(x, y, width, height) {
                if b[ny * width + nx] {
                    return true;
                }
            }
        }
    }

    false
}

fn neighbors(x: usize, y: usize, width: usize, height: usize) -> Vec<(usize, usize)> {
    let mut result = Vec::with_capacity(4);
    if x > 0 {
        result.push((x - 1, y));
    }
    if x + 1 < width {
        result.push((x + 1, y));
    }
    if y > 0 {
        result.push((x, y - 1));
    }
    if y + 1 < height {
        result.push((x, y + 1));
    }
    result
}
