// Generated by `cargo run -p wdn-enumerate`. Do not edit by hand.

use crate::{
    BaseSprite, BaseSpriteCenter, BaseSpriteEast, BaseSpriteSouth, TopSprite, TopSpriteCenter,
    TopSpriteEast, TopSpriteSouth, TopSpriteSouthEast,
};

impl BaseSprite {
    /// The tile offset of this sprite into `wall_spritesheet.svg`.
    pub fn id(&self) -> u16 {
        match self.normalize() {
            BaseSprite { center: BaseSpriteCenter::None, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 0,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 1,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 2,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::Door, east: BaseSpriteEast::None } => 3,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::StairN, east: BaseSpriteEast::None } => 4,
            BaseSprite { center: BaseSpriteCenter::WallHorizontal, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 5,
            BaseSprite { center: BaseSpriteCenter::WallInverseCorner, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 6,
            BaseSprite { center: BaseSpriteCenter::WallHorizontal, south: BaseSpriteSouth::Door, east: BaseSpriteEast::None } => 7,
            BaseSprite { center: BaseSpriteCenter::WallInverseCorner, south: BaseSpriteSouth::StairN, east: BaseSpriteEast::None } => 8,
            BaseSprite { center: BaseSpriteCenter::WallFull, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 9,
            BaseSprite { center: BaseSpriteCenter::WallFull, south: BaseSpriteSouth::StairNFull, east: BaseSpriteEast::None } => 10,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::None, east: BaseSpriteEast::Door } => 11,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::None, east: BaseSpriteEast::Door } => 12,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::Door, east: BaseSpriteEast::Door } => 13,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::StairN, east: BaseSpriteEast::Door } => 14,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::None, east: BaseSpriteEast::StairN } => 15,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::None, east: BaseSpriteEast::StairN } => 16,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::Door, east: BaseSpriteEast::StairN } => 17,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::StairN, east: BaseSpriteEast::StairN } => 18,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::None, east: BaseSpriteEast::StairS } => 19,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::None, east: BaseSpriteEast::StairS } => 20,
            BaseSprite { center: BaseSpriteCenter::WallCorner, south: BaseSpriteSouth::Door, east: BaseSpriteEast::StairS } => 21,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::StairN, east: BaseSpriteEast::StairS } => 22,
            BaseSprite { center: BaseSpriteCenter::WallVertical, south: BaseSpriteSouth::StairNFull, east: BaseSpriteEast::StairS } => 23,
            BaseSprite { center: BaseSpriteCenter::StairN, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 24,
            BaseSprite { center: BaseSpriteCenter::StairNFull, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 25,
            BaseSprite { center: BaseSpriteCenter::StairS, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 26,
            BaseSprite { center: BaseSpriteCenter::StairSFull, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 27,
            BaseSprite { center: BaseSpriteCenter::StairE, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 28,
            BaseSprite { center: BaseSpriteCenter::StairEFull, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 29,
            BaseSprite { center: BaseSpriteCenter::StairW, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 30,
            BaseSprite { center: BaseSpriteCenter::StairWFull, south: BaseSpriteSouth::None, east: BaseSpriteEast::None } => 31,
            _ => unreachable!("normalize() produced a sprite with no assigned id: {self:?}"),
        }
    }
}

impl TopSprite {
    /// The tile offset of this sprite into `wall_spritesheet.svg`.
    pub fn id(&self) -> u16 {
        match self.normalize() {
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::None, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 0,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 32,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairN, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 33,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairE, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 34,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairW, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 35,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 36,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairNFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 37,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::None } => 38,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::StairN, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 39,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairEFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 40,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairWFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 41,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 42,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::StairNFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 43,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::None } => 44,
            TopSprite { center: TopSpriteCenter::WallInverseCorner, south: TopSpriteSouth::StairN, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 45,
            TopSprite { center: TopSpriteCenter::WallHorizontal, south: TopSpriteSouth::StairEFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 46,
            TopSprite { center: TopSpriteCenter::WallFull, south: TopSpriteSouth::StairNFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 47,
            TopSprite { center: TopSpriteCenter::WallInverseCorner, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::None } => 48,
            TopSprite { center: TopSpriteCenter::WallInverseCorner, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 49,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::Door } => 50,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::StairN, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::Door } => 51,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairEFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::Door } => 52,
            TopSprite { center: TopSpriteCenter::None, south: TopSpriteSouth::StairWFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::Door } => 53,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::Door } => 54,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::StairNFull, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::Door } => 55,
            TopSprite { center: TopSpriteCenter::WallVertical, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::Door } => 56,
            TopSprite { center: TopSpriteCenter::Door, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 57,
            TopSprite { center: TopSpriteCenter::Door, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 58,
            TopSprite { center: TopSpriteCenter::Door, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::None } => 59,
            TopSprite { center: TopSpriteCenter::StairS, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 60,
            TopSprite { center: TopSpriteCenter::StairS, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 61,
            TopSprite { center: TopSpriteCenter::StairS, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::None } => 62,
            TopSprite { center: TopSpriteCenter::StairSFull, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 63,
            TopSprite { center: TopSpriteCenter::StairSFull, south: TopSpriteSouth::StairN, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 64,
            TopSprite { center: TopSpriteCenter::StairSFull, south: TopSpriteSouth::WallHorizontal, south_east: TopSpriteSouthEast::None, east: TopSpriteEast::None } => 65,
            TopSprite { center: TopSpriteCenter::StairSFull, south: TopSpriteSouth::WallCorner, south_east: TopSpriteSouthEast::StairN, east: TopSpriteEast::None } => 66,
            _ => unreachable!("normalize() produced a sprite with no assigned id: {self:?}"),
        }
    }
}
