use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::Path;

use wdn_enumerate::{
    BaseSprite, BaseSpriteCenter, BaseSpriteEast, BaseSpriteSouth, TopSprite, TopSpriteCenter,
    TopSpriteEast, TopSpriteSouth, TopSpriteSouthEast,
};

const TILE_WIDTH: u32 = 200;
const TILE_HEIGHT: u32 = 400;
const SPRITES_PER_ROW: u32 = 16;
const INKSCAPE_NS: &str = "http://www.inkscape.org/namespaces/inkscape";

/// Normalizes and deduplicates `base_sprites` and `top_sprites`, then renders them into a
/// single spritesheet SVG (base tiles first, followed by top tiles) by layering the parts
/// copied from `base_parts_path`/`top_parts_path`, writing the result to `output_path`.
pub fn generate_spritesheet(
    base_sprites: &[BaseSprite],
    base_parts_path: &Path,
    top_sprites: &[TopSprite],
    top_parts_path: &Path,
    output_path: &Path,
) -> std::io::Result<()> {
    let base_parts = extract_labeled_parts(&fs::read_to_string(base_parts_path)?);
    let top_parts = extract_labeled_parts(&fs::read_to_string(top_parts_path)?);

    let base_tiles = normalized_unique(base_sprites, BaseSprite::normalize);
    let mut top_tiles = normalized_unique(top_sprites, TopSprite::normalize);
    // The empty top sprite duplicates the empty base sprite already first in the sheet.
    if top_tiles.first() == Some(&TopSprite::EMPTY) {
        top_tiles.remove(0);
    }

    let mut tiles: Vec<(String, Vec<String>)> = base_tiles
        .iter()
        .map(|&sprite| {
            let labels = [
                center_label(sprite.center),
                south_label(sprite.south),
                east_label(sprite.east),
            ];
            (
                format!("{sprite:?}"),
                resolve_layers(&labels, &base_parts, base_parts_path),
            )
        })
        .collect();
    tiles.extend(top_tiles.iter().map(|&sprite| {
        let labels = [
            center_top_label(sprite.center),
            south_top_label(sprite.south),
            south_east_top_label(sprite.south_east),
            east_top_label(sprite.east),
        ];
        (
            format!("{sprite:?}"),
            resolve_layers(&labels, &top_parts, top_parts_path),
        )
    }));

    write_spritesheet(&tiles, output_path)
}

/// Generates `impl BaseSprite::id`/`impl TopSprite::id` methods that return each sprite's
/// tile offset into the spritesheet written by [`generate_spritesheet`], writing the
/// generated source to `output_path`.
pub fn generate_sprite_ids(
    base_sprites: &[BaseSprite],
    top_sprites: &[TopSprite],
    output_path: &Path,
) -> std::io::Result<()> {
    let base_tiles = normalized_unique(base_sprites, BaseSprite::normalize);
    let mut top_tiles = normalized_unique(top_sprites, TopSprite::normalize);
    let empty_top_removed = top_tiles.first() == Some(&TopSprite::EMPTY);
    if empty_top_removed {
        top_tiles.remove(0);
    }

    let empty_base_id = base_tiles
        .iter()
        .position(|&sprite| sprite == BaseSprite::EMPTY)
        .expect("wall_spritesheet.svg always includes the empty base sprite");

    let mut base_arms = String::new();
    for (id, &sprite) in base_tiles.iter().enumerate() {
        base_arms.push_str(&format!(
            "            {} => {id},\n",
            base_sprite_pattern(sprite)
        ));
    }

    let mut top_arms = String::new();
    if empty_top_removed {
        top_arms.push_str(&format!(
            "            {} => {empty_base_id},\n",
            top_sprite_pattern(TopSprite::EMPTY)
        ));
    }
    for (offset, &sprite) in top_tiles.iter().enumerate() {
        let id = base_tiles.len() + offset;
        top_arms.push_str(&format!(
            "            {} => {id},\n",
            top_sprite_pattern(sprite)
        ));
    }

    let mut code = String::new();
    code.push_str("// Generated by `cargo run -p wdn-enumerate`. Do not edit by hand.\n\n");
    code.push_str("use crate::{\n");
    code.push_str("    BaseSprite, BaseSpriteCenter, BaseSpriteEast, BaseSpriteSouth, TopSprite, TopSpriteCenter,\n");
    code.push_str("    TopSpriteEast, TopSpriteSouth, TopSpriteSouthEast,\n");
    code.push_str("};\n\n");
    code.push_str("impl BaseSprite {\n");
    code.push_str("    /// The tile offset of this sprite into `wall_spritesheet.svg`.\n");
    code.push_str("    pub fn id(&self) -> u16 {\n");
    code.push_str("        match self.normalize() {\n");
    code.push_str(&base_arms);
    code.push_str("            _ => unreachable!(\"normalize() produced a sprite with no assigned id: {self:?}\"),\n");
    code.push_str("        }\n    }\n}\n\n");
    code.push_str("impl TopSprite {\n");
    code.push_str("    /// The tile offset of this sprite into `wall_spritesheet.svg`.\n");
    code.push_str("    pub fn id(&self) -> u16 {\n");
    code.push_str("        match self.normalize() {\n");
    code.push_str(&top_arms);
    code.push_str("            _ => unreachable!(\"normalize() produced a sprite with no assigned id: {self:?}\"),\n");
    code.push_str("        }\n    }\n}\n");

    fs::write(output_path, code)
}

/// Normalizes `sprites`, keeping only the first occurrence of each distinct value.
fn normalized_unique<T: Copy + Eq + std::hash::Hash>(
    sprites: &[T],
    normalize: impl Fn(T) -> T,
) -> Vec<T> {
    let mut seen = HashSet::new();
    sprites
        .iter()
        .copied()
        .map(normalize)
        .filter(|sprite| seen.insert(*sprite))
        .collect()
}

/// Looks up each of `labels` in `parts`, cloning the matching SVG fragments.
fn resolve_layers(
    labels: &[&str],
    parts: &HashMap<String, String>,
    parts_path: &Path,
) -> Vec<String> {
    labels
        .iter()
        .map(|label| {
            parts
                .get(*label)
                .unwrap_or_else(|| panic!("missing part `{label}` in {}", parts_path.display()))
                .clone()
        })
        .collect()
}

/// Lays `tiles` out in a grid and writes the resulting spritesheet SVG to `output_path`.
fn write_spritesheet(tiles: &[(String, Vec<String>)], output_path: &Path) -> std::io::Result<()> {
    let columns = SPRITES_PER_ROW;
    let rows = (tiles.len() as u32).div_ceil(columns);
    let sheet_width = columns * TILE_WIDTH;
    let sheet_height = rows * TILE_HEIGHT;

    let mut groups = Vec::with_capacity(tiles.len());
    for (index, (name, layers)) in tiles.iter().enumerate() {
        let x = (index as u32 % columns) * TILE_WIDTH;
        let y = (index as u32 / columns) * TILE_HEIGHT;
        let name = escape_xml_attribute(name);

        let mut group =
            format!("  <g inkscape:label=\"{name}\" transform=\"translate({x},{y})\">\n");
        for layer in layers {
            group.push_str(layer);
            group.push('\n');
        }
        group.push_str("  </g>\n");
        groups.push(group);
    }
    // Reverse the tiles' document order; each keeps its original grid position.
    let body: String = groups.into_iter().rev().collect();

    let svg = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n\
         <svg width=\"{sheet_width}\" height=\"{sheet_height}\" viewBox=\"0 0 {sheet_width} {sheet_height}\" \
         xmlns=\"http://www.w3.org/2000/svg\" xmlns:inkscape=\"{INKSCAPE_NS}\" \
         xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\">\n{body}</svg>\n"
    );

    fs::write(output_path, svg)
}

/// Renders `sprite` as a `BaseSprite { .. }` struct pattern using the actual Rust variant
/// names, for use as a `match` arm in generated code.
fn base_sprite_pattern(sprite: BaseSprite) -> String {
    format!(
        "BaseSprite {{ center: BaseSpriteCenter::{}, south: BaseSpriteSouth::{}, east: BaseSpriteEast::{} }}",
        base_center_ident(sprite.center),
        base_south_ident(sprite.south),
        base_east_ident(sprite.east),
    )
}

/// Renders `sprite` as a `TopSprite { .. }` struct pattern using the actual Rust variant
/// names, for use as a `match` arm in generated code.
fn top_sprite_pattern(sprite: TopSprite) -> String {
    format!(
        "TopSprite {{ center: TopSpriteCenter::{}, south: TopSpriteSouth::{}, south_east: TopSpriteSouthEast::{}, east: TopSpriteEast::{} }}",
        top_center_ident(sprite.center),
        top_south_ident(sprite.south),
        top_south_east_ident(sprite.south_east),
        top_east_ident(sprite.east),
    )
}

fn base_center_ident(center: BaseSpriteCenter) -> &'static str {
    match center {
        BaseSpriteCenter::None => "None",
        BaseSpriteCenter::WallCorner => "WallCorner",
        BaseSpriteCenter::WallVertical => "WallVertical",
        BaseSpriteCenter::WallHorizontal => "WallHorizontal",
        BaseSpriteCenter::WallInverseCorner => "WallInverseCorner",
        BaseSpriteCenter::WallFull => "WallFull",
        BaseSpriteCenter::StairN => "StairN",
        BaseSpriteCenter::StairNFull => "StairNFull",
        BaseSpriteCenter::StairS => "StairS",
        BaseSpriteCenter::StairSFull => "StairSFull",
        BaseSpriteCenter::StairE => "StairE",
        BaseSpriteCenter::StairEFull => "StairEFull",
        BaseSpriteCenter::StairW => "StairW",
        BaseSpriteCenter::StairWFull => "StairWFull",
    }
}

fn base_south_ident(south: BaseSpriteSouth) -> &'static str {
    match south {
        BaseSpriteSouth::None => "None",
        BaseSpriteSouth::Door => "Door",
    }
}

fn base_east_ident(east: BaseSpriteEast) -> &'static str {
    match east {
        BaseSpriteEast::None => "None",
        BaseSpriteEast::Door => "Door",
        BaseSpriteEast::StairN => "StairN",
        BaseSpriteEast::StairS => "StairS",
    }
}

fn top_center_ident(center: TopSpriteCenter) -> &'static str {
    match center {
        TopSpriteCenter::None => "None",
        TopSpriteCenter::WallCorner => "WallCorner",
        TopSpriteCenter::WallVertical => "WallVertical",
        TopSpriteCenter::WallHorizontal => "WallHorizontal",
        TopSpriteCenter::WallInverseCorner => "WallInverseCorner",
        TopSpriteCenter::WallFull => "WallFull",
        TopSpriteCenter::Door => "Door",
    }
}

fn top_south_ident(south: TopSpriteSouth) -> &'static str {
    match south {
        TopSpriteSouth::None => "None",
        TopSpriteSouth::Door => "Door",
        TopSpriteSouth::WallCorner => "WallCorner",
        TopSpriteSouth::WallHorizontal => "WallHorizontal",
        TopSpriteSouth::StairN => "StairN",
        TopSpriteSouth::StairNFull => "StairNFull",
        TopSpriteSouth::StairE => "StairE",
        TopSpriteSouth::StairEFull => "StairEFull",
        TopSpriteSouth::StairW => "StairW",
        TopSpriteSouth::StairWFull => "StairWFull",
    }
}

fn top_south_east_ident(south_east: TopSpriteSouthEast) -> &'static str {
    match south_east {
        TopSpriteSouthEast::None => "None",
        TopSpriteSouthEast::StairN => "StairN",
        TopSpriteSouthEast::StairW => "StairW",
        TopSpriteSouthEast::StairWFull => "StairWFull",
    }
}

fn top_east_ident(east: TopSpriteEast) -> &'static str {
    match east {
        TopSpriteEast::None => "None",
        TopSpriteEast::Door => "Door",
        TopSpriteEast::StairW => "StairW",
        TopSpriteEast::StairWFull => "StairWFull",
    }
}

fn center_label(center: BaseSpriteCenter) -> &'static str {
    match center {
        BaseSpriteCenter::None => "CenterNone",
        BaseSpriteCenter::WallCorner => "CenterWallCorner",
        BaseSpriteCenter::WallVertical => "CenterWallVertical",
        BaseSpriteCenter::WallHorizontal => "CenterWallHorizontal",
        BaseSpriteCenter::WallInverseCorner => "CenterWallInverseCorner",
        BaseSpriteCenter::WallFull => "CenterWallFull",
        BaseSpriteCenter::StairN => "CenterStairN",
        BaseSpriteCenter::StairNFull => "CenterStairNFull",
        BaseSpriteCenter::StairS => "CenterStairS",
        BaseSpriteCenter::StairSFull => "CenterStairSFull",
        BaseSpriteCenter::StairE => "CenterStairE",
        BaseSpriteCenter::StairEFull => "CenterStairEFull",
        BaseSpriteCenter::StairW => "CenterStairW",
        BaseSpriteCenter::StairWFull => "CenterStairWFull",
    }
}

fn south_label(south: BaseSpriteSouth) -> &'static str {
    match south {
        BaseSpriteSouth::None => "SouthNone",
        BaseSpriteSouth::Door => "SouthDoor",
    }
}

fn east_label(east: BaseSpriteEast) -> &'static str {
    match east {
        BaseSpriteEast::None => "EastNone",
        BaseSpriteEast::Door => "EastDoor",
        BaseSpriteEast::StairN => "EastStairN",
        BaseSpriteEast::StairS => "EastStairS",
    }
}

fn center_top_label(center: TopSpriteCenter) -> &'static str {
    match center {
        TopSpriteCenter::None => "CenterNone",
        TopSpriteCenter::WallCorner => "CenterWallCorner",
        TopSpriteCenter::WallVertical => "CenterWallVertical",
        TopSpriteCenter::WallHorizontal => "CenterWallHorizontal",
        TopSpriteCenter::WallInverseCorner => "CenterWallInverseCorner",
        TopSpriteCenter::WallFull => "CenterWallFull",
        TopSpriteCenter::Door => "Corner_Door",
    }
}

fn south_top_label(south: TopSpriteSouth) -> &'static str {
    match south {
        TopSpriteSouth::None => "SouthNone",
        TopSpriteSouth::Door => "SouthDoor",
        TopSpriteSouth::WallCorner => "SouthCorner",
        TopSpriteSouth::WallHorizontal => "SouthHorizontal",
        TopSpriteSouth::StairN => "SouthStairN",
        TopSpriteSouth::StairNFull => "SouthStairNFull",
        TopSpriteSouth::StairE => "SouthStairE",
        TopSpriteSouth::StairEFull => "SouthStairEFull",
        TopSpriteSouth::StairW => "SouthStairW",
        TopSpriteSouth::StairWFull => "SouthStairWFull",
    }
}

fn south_east_top_label(south_east: TopSpriteSouthEast) -> &'static str {
    match south_east {
        TopSpriteSouthEast::None => "SouthEastNone",
        TopSpriteSouthEast::StairN => "SouthEastStairN",
        TopSpriteSouthEast::StairW => "SouthEastStairW",
        TopSpriteSouthEast::StairWFull => "SouthEastStairWFull",
    }
}

fn east_top_label(east: TopSpriteEast) -> &'static str {
    match east {
        TopSpriteEast::None => "EastNone",
        TopSpriteEast::Door => "EastDoor",
        TopSpriteEast::StairW => "EastStairW",
        TopSpriteEast::StairWFull => "EastStairWFull",
    }
}

fn escape_xml_attribute(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Collects every named part group (`inkscape:label`) keyed by that label, forcing each
/// to render since the source file hides all but one part per layer with `display:none`.
fn extract_labeled_parts(svg: &str) -> HashMap<String, String> {
    let doc = roxmltree::Document::parse(svg).expect("failed to parse parts svg");
    let mut parts = HashMap::new();

    for node in doc.descendants() {
        if !node.has_tag_name("g") {
            continue;
        }
        // Skip the top-level Center/South/East layer groups; only keep the named parts.
        if node.attribute((INKSCAPE_NS, "groupmode")) == Some("layer") {
            continue;
        }
        let Some(label) = node.attribute((INKSCAPE_NS, "label")) else {
            continue;
        };

        let raw = &svg[node.range()];
        let visible = raw.replacen("display:none", "display:inline", 1);
        parts.insert(label.to_string(), visible);
    }

    parts
}
